### ISSUE TITLE
Add "Microformats2" theme support check

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-uf2#12]
Add a check if theme supports Microformats2 (https://github.com/pfefferle/SemPress/blob/master/sempress/functions.php#L101) to enable/disable the plugin. Perhaps we have to rewrite the plugin a bit for that use case.

**Comment by dshanske** [comment]
Considering the functionality of TGM, which is used for themes as well as plugins, we could have functions that could be called by a theme, and enabled if the theme doesn't support it.

**Comment by pfefferle** [comment]
@dshanske What do you think about my quick rewrite?

**Comment by dshanske** [comment]
Much cleaner. Will need to pull a copy down.
