### ISSUE TITLE
Theme display issue with Twenty Fourteen

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-uf2#15]
I'm not currently using it, so it's not a priority (and it may not be uf2s fault based on my brief tests), but so everyone is aware, I'll mention that when using the standard WP Twenty Fourteen theme in conjunction with uf2, the display of the site is thrown out of whack and it only displays the left column and compacts the main content area into ~300px rather than the full ~900px.  For those familiar the 3x2 grid of featured posts on the front page displays as a single 1x6 column instead, (akin to making it look like its outputting for a mobile platform rather than desktop).

I've used several dozen other themes (including most of the WordPress default yearly themes) in conjunction with uf2 and haven't seen anything like this, which makes me think it's a bug with the Twenty Fourteen theme.

I'll crosspost this to WP.org so they're aware too.

**Comment by dshanske** [comment]
It is the fact that the theme styles hentry

**Comment by chrisaldrich** [comment]
<a href="http://stream.boffosocko.com/2016/theme-display-issue-with-twenty-fourteen-issue-15-pfefferlewordpress-uf2-im" class="u-in-reply-to"></a><a href="http://stream.boffosocko.com/2016/wordpress-support-twenty-fourteen-display-error-id-mentioned-this-error" class="u-in-reply-to"></a><a href="https://github.com/pfefferle/wordpress-uf2/issues/15" class="u-in-reply-to"></a>Thanks @dshanske, I figured it was either that or one of the other mf2 tags being used for styling rather than semantics.
